config/routes.rb
MonitoringSys::Application.routes.draw do
  
  get "schedule_details/index"

  resources :url_request_responses
  resources :schedule_details, only: [:index]
  get "montioring_sys/index"

end

app/models/schedule_detail.rb
class ScheduleDetail
  include Mongoid::Document
  include SchedulerJob
  field :start_time, type: DateTime
  field :end_time, type: DateTime, :default => "Pending.."
  field :status_result, type: String
  field :response_message, type: String
  belongs_to :url_request_response
  scope :include_associated_classes, includes(:url_request_response)
  validates :start_time, :end_time, :status_result, 
            :response_messagev, :presence => true
end

app/models/url_request_response.rb
class UrlRequestResponse
  include Mongoid::Document
  require 'mongo_patch_id'
  field :url, type: String
  field :http_verb, type: String
  field :http_verb, type: String
  field :request_body, type: String
  field :expected_response_header, type: String
  field :expected_response_body, type: String
  field :timeout, type: String
  field :object_type, type: String
  field :time_to_run, type: DateTime
  has_many :schedule_details, dependent: :destroy
  validates :url, :presence => { :message => 'Url can not be blank'}
  validates :http_verb, :presence => { :message => 'Http request method can not be blank'}
  validates :expected_response_header, :presence => { :message => 'Expected response header can not be blank'}
  validates :expected_response_body, :presence => { :message => 'Expected response body can not be blank'}
  validates :timeout, :presence => { :message => 'Timeout can not be blank'}
  validates :object_type, :presence => { :message => 'Object type can not be blank'}
  validates :time_to_run, :presence => { :message => 'Time to run can not be blank'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/montioring_sys_controller.rb
class MontioringSysController < ApplicationController
  def index
      @http_verbs = {}
      @object_types = {}
  end
end

app/controllers/schedule_details_controller.rb
class ScheduleDetailsController < ApplicationController
  def index
  	@schedule_details = ScheduleDetail.include_associated_classes
  end
end

app/controllers/url_request_responses_controller.rb
class UrlRequestResponsesController < ApplicationController
  # GET /url_request_responses
  # GET /url_request_responses.json
  def index
    @url_request_responses = UrlRequestResponse.all#.only(:url, :http_verb, :timeout, :object_type, :time_to_run)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @url_request_responses }
    end
  end

  # GET /url_request_responses/1
  # GET /url_request_responses/1.json
  def show
    @url_request_response = UrlRequestResponse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @url_request_response }
    end
  end

  # GET /url_request_responses/new
  # GET /url_request_responses/new.json
  def new
    @url_request_response = UrlRequestResponse.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @url_request_response }
    end
  end

  # GET /url_request_responses/1/edit
  def edit
    @url_request_response = UrlRequestResponse.find(params[:id])
  end

  # POST /url_request_responses
  # POST /url_request_responses.json
  def create
    @url_request_response = UrlRequestResponse.new(params[:url_request_response])

    respond_to do |format|
      if @url_request_response.save
        format.html { redirect_to @url_request_response, notice: 'Url request response was successfully created.' }
        format.json { render json: @url_request_response, status: :created, location: @url_request_response }
      else
        format.html { render action: "new" }
        format.json { render json: @url_request_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /url_request_responses/1
  # PUT /url_request_responses/1.json
  def update
    @url_request_response = UrlRequestResponse.find(params[:id])

    respond_to do |format|
      if @url_request_response.update_attributes(params[:url_request_response])
        format.html { redirect_to @url_request_response, notice: 'Url request response was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @url_request_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /url_request_responses/1
  # DELETE /url_request_responses/1.json
  def destroy
    @url_request_response = UrlRequestResponse.find(params[:id])
    @url_request_response.destroy

    respond_to do |format|
      format.html { redirect_to url_request_responses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/montioring_sys_helper.rb
module MontioringSysHelper
end

app/helpers/schedule_details_helper.rb
module ScheduleDetailsHelper
end

app/helpers/url_request_responses_helper.rb
module UrlRequestResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MonitoringSys</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%#= stylesheet_link_tag    "jquery.dataTables", :media => "all" %>
  <%#= stylesheet_link_tag    "demo_page", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%#= javascript_include_tag "jquery.dataTables" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/montioring_sys/index.html.erb
<center class="top-twenty">
<div class="dashboard-container span6">
	<div class="third-party-url">
		<%= text_field_tag 'ds-url', nil, class: "input-block-level", placeholder: 'Enter URL here' %>
	</div>
	<div class="http-verbs" style="float: left;">
		<%= select_tag 'http-method', options_for_select(@http_verbs.collect{ |u| [u[:name], u[:id]] }) %>
	</div>

	<div class="request-objects" style="float: right;">
		<%= select_tag 'request-object-type', options_for_select(@object_types.collect{ |u| [u[:name], u[:id]] }) %>
	</div>

	<div class="request-header-container" style="float: left;" id="req-header">
		<%= label_tag 'req-header-content', 'Request header: ' %>
		<%= text_area_tag  'req-header-content' %>
	</div>

	<div class="request-body-container" id="post-req-body">
		<%= label_tag 'post-req-body-content', 'Request body: ' %>
		<%= text_area_tag  'post-req-body-content' %>
	</div>

	<div class="request-timeout" style="float: left;" id="req-timeout-container">
		<%= label_tag 'req-timeout-value', 'Request timeout: ' %>
		<%= text_field_tag 'req-timeout-value' %>
	</div>

	<div class="response-header-container" id="res-header">
		<%= label_tag 'res-header-content', 'Response header: ' %>
		<%= text_area_tag  'res-header-content' %>
	</div>

	<div class="response-body-container" style="float: left;" id="res-header">
		<%= label_tag 'res-body-content', 'Response body: ' %>
		<%= text_area_tag  'res-body-content' %>
	</div>

	<div class="req-button" style="float: right;margin-top: 33px;">
		<%= submit_tag "Send", class: "btn btn-success" %>
	</div>
	
</div>
</center>

app/views/schedule_details/index.html.erb
<div id="schedule_details"></div>
<%#= @schedule_details.to_json %>
<script type="text/javascript">
  $(function() {
  // Blog is the app name
  window.router = new MonitoringSys.Routers.ScheduleDetailsRouter({schedule_details: <%= @schedule_details.to_json({include: :url_request_response}).html_safe -%>});
  Backbone.history.start();
  });
</script>

app/views/url_request_responses/_form.html.erb
<%= form_for(@url_request_response) do |f| %>
  <% if @url_request_response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url_request_response.errors.count, "error") %> prohibited this url_request_response from being saved:</h2>

      <ul>
      <% @url_request_response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :verb_id %><br />
    <%= f.number_field :verb_id %>
  </div>
  <div class="field">
    <%= f.label :request_header %><br />
    <%= f.text_area :request_header %>
  </div>
  <div class="field">
    <%= f.label :request_body %><br />
    <%= f.text_area :request_body %>
  </div>
  <div class="field">
    <%= f.label :response_header %><br />
    <%= f.text_area :response_header %>
  </div>
  <div class="field">
    <%= f.label :response_body %><br />
    <%= f.text_area :response_body %>
  </div>
  <div class="field">
    <%= f.label :timeout %><br />
    <%= f.number_field :timeout %>
  </div>
  <div class="field">
    <%= f.label :request_object_type_id %><br />
    <%= f.number_field :request_object_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/url_request_responses/edit.html.erb
<h1>Editing url_request_response</h1>

<%= render 'form' %>

<%= link_to 'Show', @url_request_response %> |
<%= link_to 'Back', url_request_responses_path %>

app/views/url_request_responses/index.html.erb
<center><div id="url_request_responses" class="absolute"></div></center>

<script type="text/javascript">
  $(function() {
    window.router = new MonitoringSys.Routers.UrlRequestResponsesRouter({url_request_responses: <%= @url_request_responses.to_json.html_safe -%>});
    Backbone.history.start();
  });
</script>

app/views/url_request_responses/new.html.erb
<h1>New url_request_response</h1>

<%= render 'form' %>

<%= link_to 'Back', url_request_responses_path %>

app/views/url_request_responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @url_request_response.url %>
</p>

<p>
  <b>Verb:</b>
  <%= @url_request_response.verb_id %>
</p>

<p>
  <b>Request header:</b>
  <%= @url_request_response.request_header %>
</p>

<p>
  <b>Request body:</b>
  <%= @url_request_response.request_body %>
</p>

<p>
  <b>Response header:</b>
  <%= @url_request_response.response_header %>
</p>

<p>
  <b>Response body:</b>
  <%= @url_request_response.response_body %>
</p>

<p>
  <b>Timeout:</b>
  <%= @url_request_response.timeout %>
</p>

<p>
  <b>Request object type:</b>
  <%= @url_request_response.request_object_type_id %>
</p>


<%= link_to 'Edit', edit_url_request_response_path(@url_request_response) %> |
<%= link_to 'Back', url_request_responses_path %>